import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sfFont = localFont({
  src: [
    {
      path: "./fonts/SFPRODISPLAYREGULAR.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYMEDIUM.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYBOLD.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/SFPRODISPLAYBLACKITALIC.woff2",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/SFPRODISPLAYHEAVYITALIC.woff2",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/SFPRODISPLAYSEMIBOLDITALIC.woff2",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/SFPRODISPLAYLIGHTITALIC.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/SFPRODISPLAYTHINITALIC.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/SFPRODISPLAYULTRALIGHTITALIC.woff2",
      weight: "200",
      style: "italic",
    },
  ],
  variable: "--font-sf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfFont.variable} antialiased overflow-x-hidden`}>
        <div className="flex flex-col min-h-screen min-w-screen">
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
